FROM eclipse-temurin:17-jdk-alpine

ENV JMETER_VERSION=5.6.3
ENV JMETER_HOME=/opt/apache-jmeter-${JMETER_VERSION}

RUN apk add --no-cache wget unzip bash curl \
    && mkdir -p /opt \
    && wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz \
    && tar -xzf apache-jmeter-${JMETER_VERSION}.tgz -C /opt \
    && rm apache-jmeter-${JMETER_VERSION}.tgz \
    && ln -s ${JMETER_HOME}/bin/jmeter /usr/local/bin/jmeter

WORKDIR /tests

CMD ["jmeter", "--version"]
