FROM mcr.microsoft.com/playwright:v1.49.0-jammy

WORKDIR /app

COPY tests/package*.json ./
RUN npm ci

RUN npx playwright install --with-deps chromium

WORKDIR /app/tests

CMD ["npm", "run", "test:e2e"]
